// Major global airports - filtered from OpenFlights data
// Only large_airport and medium_airport types
// Limited to ~5-6 key airports per major country for global distribution

export type MajorAirport = {
  iata: string;
  name: string;
  city: string;
  country: string;
  countryName: string;
  lat: number;
  lng: number;
  type: "large_airport" | "medium_airport";
  isHub?: boolean;
};

export const MAJOR_AIRPORTS: MajorAirport[] = [
  // UNITED STATES (6 airports)
  {
    iata: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "US",
    countryName: "United States",
    lat: 40.6413,
    lng: -73.7781,
    type: "large_airport",
    isHub: true,
  },
  {
    iata: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "US",
    countryName: "United States",
    lat: 33.9425,
    lng: -118.408,
    type: "large_airport",
  },
  {
    iata: "ORD",
    name: "O'Hare International Airport",
    city: "Chicago",
    country: "US",
    countryName: "United States",
    lat: 41.9742,
    lng: -87.9073,
    type: "large_airport",
  },
  {
    iata: "MIA",
    name: "Miami International Airport",
    city: "Miami",
    country: "US",
    countryName: "United States",
    lat: 25.7959,
    lng: -80.287,
    type: "large_airport",
  },
  {
    iata: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
    country: "US",
    countryName: "United States",
    lat: 32.8998,
    lng: -97.0403,
    type: "large_airport",
  },
  {
    iata: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    country: "US",
    countryName: "United States",
    lat: 37.6213,
    lng: -122.379,
    type: "large_airport",
  },

  // UNITED KINGDOM (5 airports)
  {
    iata: "LHR",
    name: "Heathrow Airport",
    city: "London",
    country: "GB",
    countryName: "United Kingdom",
    lat: 51.47,
    lng: -0.4543,
    type: "large_airport",
    isHub: true,
  },
  {
    iata: "LGW",
    name: "Gatwick Airport",
    city: "London",
    country: "GB",
    countryName: "United Kingdom",
    lat: 51.1537,
    lng: -0.1821,
    type: "large_airport",
  },
  {
    iata: "MAN",
    name: "Manchester Airport",
    city: "Manchester",
    country: "GB",
    countryName: "United Kingdom",
    lat: 53.3537,
    lng: -2.275,
    type: "large_airport",
  },
  {
    iata: "EDI",
    name: "Edinburgh Airport",
    city: "Edinburgh",
    country: "GB",
    countryName: "United Kingdom",
    lat: 55.95,
    lng: -3.3725,
    type: "medium_airport",
  },
  {
    iata: "BHX",
    name: "Birmingham Airport",
    city: "Birmingham",
    country: "GB",
    countryName: "United Kingdom",
    lat: 52.4539,
    lng: -1.748,
    type: "medium_airport",
  },

  // INDIA (6 airports)
  {
    iata: "DEL",
    name: "Indira Gandhi International Airport",
    city: "Delhi",
    country: "IN",
    countryName: "India",
    lat: 28.5665,
    lng: 77.1031,
    type: "large_airport",
    isHub: true,
  },
  {
    iata: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "IN",
    countryName: "India",
    lat: 19.0896,
    lng: 72.8656,
    type: "large_airport",
    isHub: true,
  },
  {
    iata: "BLR",
    name: "Kempegowda International Airport",
    city: "Bangalore",
    country: "IN",
    countryName: "India",
    lat: 13.1986,
    lng: 77.7066,
    type: "large_airport",
  },
  {
    iata: "MAA",
    name: "Chennai International Airport",
    city: "Chennai",
    country: "IN",
    countryName: "India",
    lat: 12.9941,
    lng: 80.1709,
    type: "large_airport",
  },
  {
    iata: "CCU",
    name: "Netaji Subhas Chandra Bose International Airport",
    city: "Kolkata",
    country: "IN",
    countryName: "India",
    lat: 22.6546,
    lng: 88.4467,
    type: "large_airport",
  },
  {
    iata: "HYD",
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
    country: "IN",
    countryName: "India",
    lat: 17.2403,
    lng: 78.4294,
    type: "large_airport",
  },

  // UAE (3 airports)
  {
    iata: "DXB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "AE",
    countryName: "United Arab Emirates",
    lat: 25.2532,
    lng: 55.3657,
    type: "large_airport",
    isHub: true,
  },
  {
    iata: "AUH",
    name: "Abu Dhabi International Airport",
    city: "Abu Dhabi",
    country: "AE",
    countryName: "United Arab Emirates",
    lat: 24.433,
    lng: 54.6511,
    type: "large_airport",
  },
  {
    iata: "SHJ",
    name: "Sharjah International Airport",
    city: "Sharjah",
    country: "AE",
    countryName: "United Arab Emirates",
    lat: 25.3286,
    lng: 55.5172,
    type: "medium_airport",
  },

  // GERMANY (5 airports)
  {
    iata: "FRA",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "DE",
    countryName: "Germany",
    lat: 50.0379,
    lng: 8.5622,
    type: "large_airport",
  },
  {
    iata: "MUC",
    name: "Munich Airport",
    city: "Munich",
    country: "DE",
    countryName: "Germany",
    lat: 48.3538,
    lng: 11.7861,
    type: "large_airport",
  },
  {
    iata: "TXL",
    name: "Berlin Tegel Airport",
    city: "Berlin",
    country: "DE",
    countryName: "Germany",
    lat: 52.5597,
    lng: 13.2877,
    type: "large_airport",
  },
  {
    iata: "DUS",
    name: "Düsseldorf Airport",
    city: "Düsseldorf",
    country: "DE",
    countryName: "Germany",
    lat: 51.2895,
    lng: 6.7668,
    type: "medium_airport",
  },
  {
    iata: "HAM",
    name: "Hamburg Airport",
    city: "Hamburg",
    country: "DE",
    countryName: "Germany",
    lat: 53.6304,
    lng: 9.9882,
    type: "medium_airport",
  },

  // FRANCE (5 airports)
  {
    iata: "CDG",
    name: "Charles de Gaulle Airport",
    city: "Paris",
    country: "FR",
    countryName: "France",
    lat: 49.0097,
    lng: 2.5479,
    type: "large_airport",
  },
  {
    iata: "ORY",
    name: "Paris Orly Airport",
    city: "Paris",
    country: "FR",
    countryName: "France",
    lat: 48.7233,
    lng: 2.3794,
    type: "large_airport",
  },
  {
    iata: "NCE",
    name: "Nice Côte d'Azur Airport",
    city: "Nice",
    country: "FR",
    countryName: "France",
    lat: 43.6584,
    lng: 7.2159,
    type: "medium_airport",
  },
  {
    iata: "LYS",
    name: "Lyon-Saint Exupéry Airport",
    city: "Lyon",
    country: "FR",
    countryName: "France",
    lat: 45.7256,
    lng: 5.0811,
    type: "medium_airport",
  },
  {
    iata: "MRS",
    name: "Marseille Provence Airport",
    city: "Marseille",
    country: "FR",
    countryName: "France",
    lat: 43.4393,
    lng: 5.2214,
    type: "medium_airport",
  },

  // JAPAN (5 airports)
  {
    iata: "HND",
    name: "Tokyo Haneda Airport",
    city: "Tokyo",
    country: "JP",
    countryName: "Japan",
    lat: 35.5494,
    lng: 139.7798,
    type: "large_airport",
  },
  {
    iata: "NRT",
    name: "Narita International Airport",
    city: "Tokyo",
    country: "JP",
    countryName: "Japan",
    lat: 35.7647,
    lng: 140.3864,
    type: "large_airport",
  },
  {
    iata: "KIX",
    name: "Kansai International Airport",
    city: "Osaka",
    country: "JP",
    countryName: "Japan",
    lat: 34.4347,
    lng: 135.2441,
    type: "large_airport",
  },
  {
    iata: "NGO",
    name: "Chubu Centrair International Airport",
    city: "Nagoya",
    country: "JP",
    countryName: "Japan",
    lat: 34.8584,
    lng: 136.8054,
    type: "medium_airport",
  },
  {
    iata: "CTS",
    name: "New Chitose Airport",
    city: "Sapporo",
    country: "JP",
    countryName: "Japan",
    lat: 42.7752,
    lng: 141.692,
    type: "medium_airport",
  },

  // CHINA (6 airports)
  {
    iata: "PEK",
    name: "Beijing Capital International Airport",
    city: "Beijing",
    country: "CN",
    countryName: "China",
    lat: 40.0799,
    lng: 116.6031,
    type: "large_airport",
  },
  {
    iata: "PVG",
    name: "Shanghai Pudong International Airport",
    city: "Shanghai",
    country: "CN",
    countryName: "China",
    lat: 31.1434,
    lng: 121.8052,
    type: "large_airport",
  },
  {
    iata: "CAN",
    name: "Guangzhou Baiyun International Airport",
    city: "Guangzhou",
    country: "CN",
    countryName: "China",
    lat: 23.3924,
    lng: 113.2988,
    type: "large_airport",
  },
  {
    iata: "CTU",
    name: "Chengdu Shuangliu International Airport",
    city: "Chengdu",
    country: "CN",
    countryName: "China",
    lat: 30.5785,
    lng: 103.9468,
    type: "large_airport",
  },
  {
    iata: "SZX",
    name: "Shenzhen Bao'an International Airport",
    city: "Shenzhen",
    country: "CN",
    countryName: "China",
    lat: 22.6393,
    lng: 113.8107,
    type: "large_airport",
  },
  {
    iata: "XIY",
    name: "Xi'an Xianyang International Airport",
    city: "Xi'an",
    country: "CN",
    countryName: "China",
    lat: 34.4471,
    lng: 108.7514,
    type: "medium_airport",
  },

  // AUSTRALIA (5 airports)
  {
    iata: "SYD",
    name: "Sydney Kingsford Smith International Airport",
    city: "Sydney",
    country: "AU",
    countryName: "Australia",
    lat: -33.9399,
    lng: 151.1753,
    type: "large_airport",
  },
  {
    iata: "MEL",
    name: "Melbourne Airport",
    city: "Melbourne",
    country: "AU",
    countryName: "Australia",
    lat: -37.669,
    lng: 144.841,
    type: "large_airport",
  },
  {
    iata: "BNE",
    name: "Brisbane Airport",
    city: "Brisbane",
    country: "AU",
    countryName: "Australia",
    lat: -27.3842,
    lng: 153.1175,
    type: "large_airport",
  },
  {
    iata: "PER",
    name: "Perth Airport",
    city: "Perth",
    country: "AU",
    countryName: "Australia",
    lat: -31.9403,
    lng: 115.9668,
    type: "medium_airport",
  },
  {
    iata: "ADL",
    name: "Adelaide Airport",
    city: "Adelaide",
    country: "AU",
    countryName: "Australia",
    lat: -34.945,
    lng: 138.5306,
    type: "medium_airport",
  },

  // BRAZIL (5 airports)
  {
    iata: "GRU",
    name: "São Paulo/Guarulhos International Airport",
    city: "São Paulo",
    country: "BR",
    countryName: "Brazil",
    lat: -23.4356,
    lng: -46.4731,
    type: "large_airport",
  },
  {
    iata: "GIG",
    name: "Rio de Janeiro/Galeão International Airport",
    city: "Rio de Janeiro",
    country: "BR",
    countryName: "Brazil",
    lat: -22.8099,
    lng: -43.2505,
    type: "large_airport",
  },
  {
    iata: "BSB",
    name: "Brasília International Airport",
    city: "Brasília",
    country: "BR",
    countryName: "Brazil",
    lat: -15.8711,
    lng: -47.9181,
    type: "large_airport",
  },
  {
    iata: "CGH",
    name: "São Paulo/Congonhas Airport",
    city: "São Paulo",
    country: "BR",
    countryName: "Brazil",
    lat: -23.6266,
    lng: -46.6554,
    type: "medium_airport",
  },
  {
    iata: "SDU",
    name: "Santos Dumont Airport",
    city: "Rio de Janeiro",
    country: "BR",
    countryName: "Brazil",
    lat: -22.9105,
    lng: -43.1631,
    type: "medium_airport",
  },

  // CANADA (5 airports)
  {
    iata: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    country: "CA",
    countryName: "Canada",
    lat: 43.6777,
    lng: -79.6248,
    type: "large_airport",
  },
  {
    iata: "YVR",
    name: "Vancouver International Airport",
    city: "Vancouver",
    country: "CA",
    countryName: "Canada",
    lat: 49.1939,
    lng: -123.1844,
    type: "large_airport",
  },
  {
    iata: "YUL",
    name: "Montréal-Pierre Elliott Trudeau International Airport",
    city: "Montreal",
    country: "CA",
    countryName: "Canada",
    lat: 45.4706,
    lng: -73.7408,
    type: "large_airport",
  },
  {
    iata: "YYC",
    name: "Calgary International Airport",
    city: "Calgary",
    country: "CA",
    countryName: "Canada",
    lat: 51.1139,
    lng: -114.0203,
    type: "medium_airport",
  },
  {
    iata: "YEG",
    name: "Edmonton International Airport",
    city: "Edmonton",
    country: "CA",
    countryName: "Canada",
    lat: 53.3097,
    lng: -113.58,
    type: "medium_airport",
  },

  // SINGAPORE (1 airport)
  {
    iata: "SIN",
    name: "Singapore Changi Airport",
    city: "Singapore",
    country: "SG",
    countryName: "Singapore",
    lat: 1.3644,
    lng: 103.9915,
    type: "large_airport",
    isHub: true,
  },

  // NETHERLANDS (1 airport)
  {
    iata: "AMS",
    name: "Amsterdam Airport Schiphol",
    city: "Amsterdam",
    country: "NL",
    countryName: "Netherlands",
    lat: 52.3086,
    lng: 4.7639,
    type: "large_airport",
    isHub: true,
  },

  // TURKEY (2 airports)
  {
    iata: "IST",
    name: "Istanbul Airport",
    city: "Istanbul",
    country: "TR",
    countryName: "Turkey",
    lat: 41.2753,
    lng: 28.7519,
    type: "large_airport",
    isHub: true,
  },
  {
    iata: "SAW",
    name: "Sabiha Gökçen International Airport",
    city: "Istanbul",
    country: "TR",
    countryName: "Turkey",
    lat: 40.8986,
    lng: 29.3092,
    type: "large_airport",
  },

  // SOUTH KOREA (2 airports)
  {
    iata: "ICN",
    name: "Incheon International Airport",
    city: "Seoul",
    country: "KR",
    countryName: "South Korea",
    lat: 37.4602,
    lng: 126.4407,
    type: "large_airport",
  },
  {
    iata: "GMP",
    name: "Gimpo International Airport",
    city: "Seoul",
    country: "KR",
    countryName: "South Korea",
    lat: 37.5583,
    lng: 126.7906,
    type: "medium_airport",
  },

  // SPAIN (4 airports)
  {
    iata: "MAD",
    name: "Adolfo Suárez Madrid-Barajas Airport",
    city: "Madrid",
    country: "ES",
    countryName: "Spain",
    lat: 40.4719,
    lng: -3.5626,
    type: "large_airport",
  },
  {
    iata: "BCN",
    name: "Barcelona-El Prat Airport",
    city: "Barcelona",
    country: "ES",
    countryName: "Spain",
    lat: 41.2971,
    lng: 2.0785,
    type: "large_airport",
  },
  {
    iata: "PMI",
    name: "Palma de Mallorca Airport",
    city: "Palma de Mallorca",
    country: "ES",
    countryName: "Spain",
    lat: 39.5517,
    lng: 2.7388,
    type: "medium_airport",
  },
  {
    iata: "AGP",
    name: "Málaga-Costa del Sol Airport",
    city: "Málaga",
    country: "ES",
    countryName: "Spain",
    lat: 36.6749,
    lng: -4.4991,
    type: "medium_airport",
  },

  // ITALY (4 airports)
  {
    iata: "FCO",
    name: "Leonardo da Vinci-Fiumicino Airport",
    city: "Rome",
    country: "IT",
    countryName: "Italy",
    lat: 41.8003,
    lng: 12.2389,
    type: "large_airport",
  },
  {
    iata: "MXP",
    name: "Milan Malpensa Airport",
    city: "Milan",
    country: "IT",
    countryName: "Italy",
    lat: 45.6306,
    lng: 8.7281,
    type: "large_airport",
  },
  {
    iata: "LIN",
    name: "Milan Linate Airport",
    city: "Milan",
    country: "IT",
    countryName: "Italy",
    lat: 45.4451,
    lng: 9.2767,
    type: "medium_airport",
  },
  {
    iata: "NAP",
    name: "Naples International Airport",
    city: "Naples",
    country: "IT",
    countryName: "Italy",
    lat: 40.886,
    lng: 14.2908,
    type: "medium_airport",
  },

  // RUSSIA (3 airports)
  {
    iata: "SVO",
    name: "Sheremetyevo International Airport",
    city: "Moscow",
    country: "RU",
    countryName: "Russia",
    lat: 55.9726,
    lng: 37.4146,
    type: "large_airport",
  },
  {
    iata: "DME",
    name: "Domodedovo International Airport",
    city: "Moscow",
    country: "RU",
    countryName: "Russia",
    lat: 55.4088,
    lng: 37.9063,
    type: "large_airport",
  },
  {
    iata: "LED",
    name: "Pulkovo Airport",
    city: "Saint Petersburg",
    country: "RU",
    countryName: "Russia",
    lat: 59.8003,
    lng: 30.2625,
    type: "medium_airport",
  },

  // MEXICO (3 airports)
  {
    iata: "MEX",
    name: "Mexico City International Airport",
    city: "Mexico City",
    country: "MX",
    countryName: "Mexico",
    lat: 19.4363,
    lng: -99.0721,
    type: "large_airport",
  },
  {
    iata: "CUN",
    name: "Cancún International Airport",
    city: "Cancún",
    country: "MX",
    countryName: "Mexico",
    lat: 21.0365,
    lng: -86.8771,
    type: "large_airport",
  },
  {
    iata: "GDL",
    name: "Guadalajara International Airport",
    city: "Guadalajara",
    country: "MX",
    countryName: "Mexico",
    lat: 20.5218,
    lng: -103.3106,
    type: "medium_airport",
  },

  // SOUTH AFRICA (2 airports)
  {
    iata: "JNB",
    name: "O.R. Tambo International Airport",
    city: "Johannesburg",
    country: "ZA",
    countryName: "South Africa",
    lat: -26.1392,
    lng: 28.246,
    type: "large_airport",
  },
  {
    iata: "CPT",
    name: "Cape Town International Airport",
    city: "Cape Town",
    country: "ZA",
    countryName: "South Africa",
    lat: -33.9648,
    lng: 18.6017,
    type: "medium_airport",
  },

  // EGYPT (2 airports)
  {
    iata: "CAI",
    name: "Cairo International Airport",
    city: "Cairo",
    country: "EG",
    countryName: "Egypt",
    lat: 30.1219,
    lng: 31.4056,
    type: "large_airport",
  },
  {
    iata: "HRG",
    name: "Hurghada International Airport",
    city: "Hurghada",
    country: "EG",
    countryName: "Egypt",
    lat: 27.1783,
    lng: 33.7994,
    type: "medium_airport",
  },

  // THAILAND (3 airports)
  {
    iata: "BKK",
    name: "Suvarnabhumi Airport",
    city: "Bangkok",
    country: "TH",
    countryName: "Thailand",
    lat: 13.69,
    lng: 100.7501,
    type: "large_airport",
  },
  {
    iata: "DMK",
    name: "Don Mueang International Airport",
    city: "Bangkok",
    country: "TH",
    countryName: "Thailand",
    lat: 13.9126,
    lng: 100.6067,
    type: "medium_airport",
  },
  {
    iata: "HKT",
    name: "Phuket International Airport",
    city: "Phuket",
    country: "TH",
    countryName: "Thailand",
    lat: 8.1132,
    lng: 98.3169,
    type: "medium_airport",
  },

  // INDONESIA (3 airports)
  {
    iata: "CGK",
    name: "Soekarno-Hatta International Airport",
    city: "Jakarta",
    country: "ID",
    countryName: "Indonesia",
    lat: -6.1256,
    lng: 106.6559,
    type: "large_airport",
  },
  {
    iata: "DPS",
    name: "Ngurah Rai International Airport",
    city: "Denpasar",
    country: "ID",
    countryName: "Indonesia",
    lat: -8.7482,
    lng: 115.1672,
    type: "medium_airport",
  },
  {
    iata: "SUB",
    name: "Juanda International Airport",
    city: "Surabaya",
    country: "ID",
    countryName: "Indonesia",
    lat: -7.3798,
    lng: 112.7869,
    type: "medium_airport",
  },

  // MALAYSIA (2 airports)
  {
    iata: "KUL",
    name: "Kuala Lumpur International Airport",
    city: "Kuala Lumpur",
    country: "MY",
    countryName: "Malaysia",
    lat: 2.7456,
    lng: 101.7099,
    type: "large_airport",
  },
  {
    iata: "BKI",
    name: "Kota Kinabalu International Airport",
    city: "Kota Kinabalu",
    country: "MY",
    countryName: "Malaysia",
    lat: 5.9372,
    lng: 116.0515,
    type: "medium_airport",
  },

  // PHILIPPINES (2 airports)
  {
    iata: "MNL",
    name: "Ninoy Aquino International Airport",
    city: "Manila",
    country: "PH",
    countryName: "Philippines",
    lat: 14.5086,
    lng: 121.0194,
    type: "large_airport",
  },
  {
    iata: "CEB",
    name: "Mactan-Cebu International Airport",
    city: "Cebu",
    country: "PH",
    countryName: "Philippines",
    lat: 10.3075,
    lng: 123.9792,
    type: "medium_airport",
  },

  // ARGENTINA (2 airports)
  {
    iata: "EZE",
    name: "Ezeiza International Airport",
    city: "Buenos Aires",
    country: "AR",
    countryName: "Argentina",
    lat: -34.8222,
    lng: -58.5358,
    type: "large_airport",
  },
  {
    iata: "AEP",
    name: "Jorge Newbery Airfield",
    city: "Buenos Aires",
    country: "AR",
    countryName: "Argentina",
    lat: -34.5592,
    lng: -58.4156,
    type: "medium_airport",
  },

  // CHILE (2 airports)
  {
    iata: "SCL",
    name: "Arturo Merino Benítez International Airport",
    city: "Santiago",
    country: "CL",
    countryName: "Chile",
    lat: -33.3928,
    lng: -70.7858,
    type: "large_airport",
  },
  {
    iata: "IPC",
    name: "Mataveri International Airport",
    city: "Easter Island",
    country: "CL",
    countryName: "Chile",
    lat: -27.1648,
    lng: -109.4219,
    type: "medium_airport",
  },

  // SWEDEN (2 airports)
  {
    iata: "ARN",
    name: "Stockholm Arlanda Airport",
    city: "Stockholm",
    country: "SE",
    countryName: "Sweden",
    lat: 59.6519,
    lng: 17.9186,
    type: "large_airport",
  },
  {
    iata: "GOT",
    name: "Gothenburg-Landvetter Airport",
    city: "Gothenburg",
    country: "SE",
    countryName: "Sweden",
    lat: 57.6628,
    lng: 12.2798,
    type: "medium_airport",
  },

  // NORWAY (2 airports)
  {
    iata: "OSL",
    name: "Oslo Airport",
    city: "Oslo",
    country: "NO",
    countryName: "Norway",
    lat: 60.1939,
    lng: 11.1004,
    type: "large_airport",
  },
  {
    iata: "BGO",
    name: "Bergen Airport Flesland",
    city: "Bergen",
    country: "NO",
    countryName: "Norway",
    lat: 60.2934,
    lng: 5.2181,
    type: "medium_airport",
  },

  // DENMARK (2 airports)
  {
    iata: "CPH",
    name: "Copenhagen Airport",
    city: "Copenhagen",
    country: "DK",
    countryName: "Denmark",
    lat: 55.6179,
    lng: 12.656,
    type: "large_airport",
  },
  {
    iata: "BLL",
    name: "Billund Airport",
    city: "Billund",
    country: "DK",
    countryName: "Denmark",
    lat: 55.7403,
    lng: 9.1522,
    type: "medium_airport",
  },

  // POLAND (2 airports)
  {
    iata: "WAW",
    name: "Warsaw Chopin Airport",
    city: "Warsaw",
    country: "PL",
    countryName: "Poland",
    lat: 52.1657,
    lng: 20.9671,
    type: "large_airport",
  },
  {
    iata: "KRK",
    name: "John Paul II International Airport Kraków-Balice",
    city: "Krakow",
    country: "PL",
    countryName: "Poland",
    lat: 50.0777,
    lng: 19.7848,
    type: "medium_airport",
  },

  // GREECE (2 airports)
  {
    iata: "ATH",
    name: "Athens International Airport",
    city: "Athens",
    country: "GR",
    countryName: "Greece",
    lat: 37.9364,
    lng: 23.9445,
    type: "large_airport",
  },
  {
    iata: "SKG",
    name: "Thessaloniki Airport",
    city: "Thessaloniki",
    country: "GR",
    countryName: "Greece",
    lat: 40.5244,
    lng: 22.9709,
    type: "medium_airport",
  },

  // PORTUGAL (2 airports)
  {
    iata: "LIS",
    name: "Lisbon Airport",
    city: "Lisbon",
    country: "PT",
    countryName: "Portugal",
    lat: 38.7813,
    lng: -9.1359,
    type: "large_airport",
  },
  {
    iata: "OPO",
    name: "Francisco Sá Carneiro Airport",
    city: "Porto",
    country: "PT",
    countryName: "Portugal",
    lat: 41.2481,
    lng: -8.6814,
    type: "medium_airport",
  },

  // AUSTRIA (2 airports)
  {
    iata: "VIE",
    name: "Vienna International Airport",
    city: "Vienna",
    country: "AT",
    countryName: "Austria",
    lat: 48.1103,
    lng: 16.5697,
    type: "large_airport",
  },
  {
    iata: "SZG",
    name: "Salzburg Airport",
    city: "Salzburg",
    country: "AT",
    countryName: "Austria",
    lat: 47.7933,
    lng: 13.0043,
    type: "medium_airport",
  },

  // SWITZERLAND (2 airports)
  {
    iata: "ZRH",
    name: "Zürich Airport",
    city: "Zurich",
    country: "CH",
    countryName: "Switzerland",
    lat: 47.4647,
    lng: 8.5492,
    type: "large_airport",
  },
  {
    iata: "GVA",
    name: "Geneva Airport",
    city: "Geneva",
    country: "CH",
    countryName: "Switzerland",
    lat: 46.2381,
    lng: 6.1089,
    type: "medium_airport",
  },

  // BELGIUM (1 airport)
  {
    iata: "BRU",
    name: "Brussels Airport",
    city: "Brussels",
    country: "BE",
    countryName: "Belgium",
    lat: 50.9014,
    lng: 4.4844,
    type: "large_airport",
  },

  // IRELAND (1 airport)
  {
    iata: "DUB",
    name: "Dublin Airport",
    city: "Dublin",
    country: "IE",
    countryName: "Ireland",
    lat: 53.4213,
    lng: -6.2701,
    type: "large_airport",
  },

  // FINLAND (1 airport)
  {
    iata: "HEL",
    name: "Helsinki-Vantaa Airport",
    city: "Helsinki",
    country: "FI",
    countryName: "Finland",
    lat: 60.3172,
    lng: 24.9633,
    type: "large_airport",
  },

  // NEW ZEALAND (2 airports)
  {
    iata: "AKL",
    name: "Auckland Airport",
    city: "Auckland",
    country: "NZ",
    countryName: "New Zealand",
    lat: -37.0082,
    lng: 174.785,
    type: "large_airport",
  },
  {
    iata: "CHC",
    name: "Christchurch Airport",
    city: "Christchurch",
    country: "NZ",
    countryName: "New Zealand",
    lat: -43.4894,
    lng: 172.532,
    type: "medium_airport",
  },

  // ISRAEL (1 airport)
  {
    iata: "TLV",
    name: "Ben Gurion Airport",
    city: "Tel Aviv",
    country: "IL",
    countryName: "Israel",
    lat: 32.0114,
    lng: 34.8867,
    type: "large_airport",
  },

  // SAUDI ARABIA (2 airports)
  {
    iata: "RUH",
    name: "King Khalid International Airport",
    city: "Riyadh",
    country: "SA",
    countryName: "Saudi Arabia",
    lat: 24.9576,
    lng: 46.6988,
    type: "large_airport",
  },
  {
    iata: "JED",
    name: "King Abdulaziz International Airport",
    city: "Jeddah",
    country: "SA",
    countryName: "Saudi Arabia",
    lat: 21.6796,
    lng: 39.1565,
    type: "large_airport",
  },

  // QATAR (1 airport)
  {
    iata: "DOH",
    name: "Hamad International Airport",
    city: "Doha",
    country: "QA",
    countryName: "Qatar",
    lat: 25.2731,
    lng: 51.608,
    type: "large_airport",
  },

  // KENYA (1 airport)
  {
    iata: "NBO",
    name: "Jomo Kenyatta International Airport",
    city: "Nairobi",
    country: "KE",
    countryName: "Kenya",
    lat: -1.3192,
    lng: 36.9278,
    type: "large_airport",
  },

  // NIGERIA (1 airport)
  {
    iata: "LOS",
    name: "Murtala Muhammed International Airport",
    city: "Lagos",
    country: "NG",
    countryName: "Nigeria",
    lat: 6.5774,
    lng: 3.3212,
    type: "large_airport",
  },

  // VIETNAM (2 airports)
  {
    iata: "SGN",
    name: "Tan Son Nhat International Airport",
    city: "Ho Chi Minh City",
    country: "VN",
    countryName: "Vietnam",
    lat: 10.8188,
    lng: 106.6519,
    type: "large_airport",
  },
  {
    iata: "HAN",
    name: "Noi Bai International Airport",
    city: "Hanoi",
    country: "VN",
    countryName: "Vietnam",
    lat: 21.2212,
    lng: 105.8067,
    type: "large_airport",
  },

  // PAKISTAN (2 airports)
  {
    iata: "KHI",
    name: "Jinnah International Airport",
    city: "Karachi",
    country: "PK",
    countryName: "Pakistan",
    lat: 24.9065,
    lng: 67.1608,
    type: "large_airport",
  },
  {
    iata: "LHE",
    name: "Allama Iqbal International Airport",
    city: "Lahore",
    country: "PK",
    countryName: "Pakistan",
    lat: 31.5216,
    lng: 74.4036,
    type: "medium_airport",
  },

  // BANGLADESH (1 airport)
  {
    iata: "DAC",
    name: "Hazrat Shahjalal International Airport",
    city: "Dhaka",
    country: "BD",
    countryName: "Bangladesh",
    lat: 23.8433,
    lng: 90.3978,
    type: "large_airport",
  },

  // SRI LANKA (1 airport)
  {
    iata: "CMB",
    name: "Bandaranaike International Airport",
    city: "Colombo",
    country: "LK",
    countryName: "Sri Lanka",
    lat: 7.1808,
    lng: 79.8841,
    type: "medium_airport",
  },
];

// Convert to GeoJSON FeatureCollection
export const AIRPORTS_GEOJSON: GeoJSON.FeatureCollection<GeoJSON.Point, {
  iata: string;
  name: string;
  city: string;
  country: string;
  countryName: string;
  type: string;
  isHub: boolean;
}> = {
  type: "FeatureCollection",
  features: MAJOR_AIRPORTS.map((airport) => ({
    type: "Feature" as const,
    geometry: {
      type: "Point" as const,
      coordinates: [airport.lng, airport.lat] as [number, number],
    },
    properties: {
      iata: airport.iata,
      name: airport.name,
      city: airport.city,
      country: airport.country,
      countryName: airport.countryName,
      type: airport.type,
      isHub: airport.isHub || false,
    },
  })),
};
